SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE `terralinks` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `terralinks`;

CREATE TABLE `po` (
  `suburb` varchar(256) NOT NULL,
  `city_town` varchar(256) NOT NULL,
  `postcode` varchar(4) NOT NULL,
  PRIMARY KEY (`suburb`,`city_town`,`postcode`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
SET FOREIGN_KEY_CHECKS=1;
